/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.moritzf.alto.v3.parser;

import gov.loc.standards.alto.ns_v3_.AltoType;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import java.io.InputStream;

/**
 * Parser for ALTO documents (V3.0-V3.1).
 */
public final class AltoParser {

    /**
     * Parses an ALTO data stream.
     */
    public static AltoType parse(InputStream stream) throws JAXBException {
        JAXBContext jaxbContext = JAXBContext.newInstance(AltoType.class);
        Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
        JAXBElement alto = (JAXBElement) jaxbUnmarshaller.unmarshal(stream);
        AltoType altoType = (AltoType) alto.getValue();
        return altoType;
    }
}
